### ISSUE TITLE
Update AAS Web UI's .vue components to use Vue's Composition API

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-aas-web-ui#36]
This will improve performance, readability, and TypeScript support and streamline importing in vue components.

## ToDo's

- [ ] Update every vue component to use composition API
- [ ] Update mixins to be composables
- [ ] Use script setup syntax

**Comment by seicke** [comment]
Status: 28 components still to be updated

```
/aas-web-ui/src/components/Dashboard/DashboardEditElement.vue
/aas-web-ui/src/components/Dashboard/DashboardElement.vue
/aas-web-ui/src/components/Plugins/SubmodelElements/HTWFuehrungskomponente.vue
/aas-web-ui/src/components/Plugins/SubmodelElements/JSONArrayProperty.vue
/aas-web-ui/src/components/Plugins/Submodels/TimeSeries_v1_1.vue
/aas-web-ui/src/components/Plugins/CADPreview.vue
/aas-web-ui/src/components/SubmodelElements/File.vue
/aas-web-ui/src/components/SubmodelElements/MultiLanguageProperty.vue
/aas-web-ui/src/components/SubmodelElements/ReferenceElement.vue
/aas-web-ui/src/components/SubmodelElements/RelationshipElement.vue
/aas-web-ui/src/components/UIComponents/GenericDataVisu.vue
/aas-web-ui/src/components/UIComponents/SubmodelElementWrapper.vue
/aas-web-ui/src/components/Widgets/AreaChart.vue
/aas-web-ui/src/components/Widgets/BarChart.vue
/aas-web-ui/src/components/Widgets/Button.vue
/aas-web-ui/src/components/Widgets/ColumnChart.vue
/aas-web-ui/src/components/Widgets/DisplayField.vue
/aas-web-ui/src/components/Widgets/DonutChart.vue
/aas-web-ui/src/components/Widgets/Gauge.vue
/aas-web-ui/src/components/Widgets/Histogram.vue
/aas-web-ui/src/components/Widgets/InputField.vue
/aas-web-ui/src/components/Widgets/Lamp.vue
/aas-web-ui/src/components/Widgets/LineChart.vue
/aas-web-ui/src/components/Widgets/RadialChart.vue
/aas-web-ui/src/components/Widgets/ScatterChart.vue
/aas-web-ui/src/components/Widgets/Switch.vue
/aas-web-ui/src/pages/Dashboard.vue
/aas-web-ui/src/pages/DashboardGroup.vue
```
